In [90]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn import metrics


In [91]:
# Dữ liệu được lấy từ 
# https://archive.ics.uci.edu/ml/datasets/Student+Performance

# Dự đoán số điểm cuối kì của học sinh (cột 32)
pd.set_option('display.max_columns', None)
df = pd.read_csv("data/student.csv")

df = df.replace('yes', value=1)
df = df.replace('no', value=0)

useful_columns = ['age', 'traveltime', 'studytime',
                  'failures', 'famrel', 'freetime',
                  'goout', 'Dalc', 'Walc', 'health',
                  'absences', 'G1', 'G2']

boolean_columns = ['schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']

# Dữ liệu không bao gồm các cột boolean
new_data = df[useful_columns]

# Dữ liệu bao gồm cả cột boolean
more_accurate_data = df[useful_columns + boolean_columns]

data = df.values

# Lấy cột số 32 làm y
y = data[:,-1:]
y = y.ravel()



In [97]:
# X từ dữ liệu bao gồm cả cột boolean
X_train_all = more_accurate_data[:100]
X_test_all= more_accurate_data[101:111]

In [98]:
# X từ dữ liệu không bao gồm các cột boolean
X_train = new_data[:100]
X_test = new_data[101:111]

y_train = y[:100]
y_test = y[101:111]

print(y_train[:3])
print(y_test[:3])

[6 6 10]
[17 14 6]


In [95]:
# Fit model cho X_train
model = LinearRegression()
model.fit(X_train, y_train)

# So sánh giữa y được tính và y dữ liệu thật
y_predict = model.predict(X_test)
print(y_predict)
print(y_test)


[17.0563132  13.06563583  5.33897439 18.34031484 10.56137204  8.17357564
 18.09056848 11.83045001 14.80252703 19.24178496]
[17 14 6 18 11 8 18 13 16 19]


In [101]:
# Fit model cho X_train_all
modelAll = LinearRegression()
modelAll.fit(X_train_all, y_train)

y_predict_all = modelAll.predict(X_test_all)
print(y_predict_all)
print(y_test)

[17.05054898 13.47908552  5.40672869 18.26693799 10.42449334  8.13746406
 18.07071126 11.80341375 14.86427848 19.18059376]
[17 14 6 18 11 8 18 13 16 19]


In [102]:
from sklearn.metrics import mean_squared_error
from math import sqrt

# So sánh độ sai của dữ liệu X_train và dữ liệu X_train_all
# Em nhận thấy khi ta tăng thêm cột thuộc tính thì độ chính xác sẽ tăng, độ sai lệch sẽ giảm
MSE = mean_squared_error(y_test, y_predict)
MSE_all = mean_squared_error(y_test, y_predict_all)
print(MSE)
print(MSE_all)

0.45199509433852453
0.38065343086472986
