In [2]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics


In [3]:
df = pd.read_csv("data/winequality-red.csv")
df


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [4]:
data = df.values

X = data[:,:-1]
y = data[:,-1:].ravel()
print(data)
print(y)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
[5. 5. 5. ... 6. 5. 6.]


In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)
print(X)

[[0.24778761 0.39726027 0.         ... 0.60629921 0.13772455 0.15384615]
 [0.28318584 0.52054795 0.         ... 0.36220472 0.20958084 0.21538462]
 [0.28318584 0.43835616 0.04       ... 0.40944882 0.19161677 0.21538462]
 ...
 [0.15044248 0.26712329 0.13       ... 0.53543307 0.25149701 0.4       ]
 [0.11504425 0.35958904 0.12       ... 0.65354331 0.22754491 0.27692308]
 [0.12389381 0.13013699 0.47       ... 0.51181102 0.19760479 0.4       ]]


In [71]:
# scaler = MinMaxScaler()
# scaler.fit(y)
# y = scaler.transform(y)
# y = y.ravel()
# print(y)

[0.4 0.4 0.4 ... 0.6 0.4 0.6]


In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)
neural_network = MLPClassifier(random_state=1,hidden_layer_sizes=(20,30), activation='tanh', solver='sgd', max_iter=300)
neural_network.fit(X_train, y_train)

c:\users\steel\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(activation='tanh', hidden_layer_sizes=(20, 30), max_iter=300,
              random_state=1, solver='sgd')

In [10]:
y_pred = neural_network.predict(X_test)
print(y_pred)
print(y_test)

[5. 5. 6. 6. 5. 5. 5. 6. 5. 6. 6. 6. 5. 6. 6. 5. 5. 6. 5. 5. 5. 5. 5. 5.
 6. 5. 6. 6. 5. 6. 5. 5. 6. 6. 5. 5. 6. 6. 6. 5. 6. 6. 6. 6. 6. 6. 6. 5.
 5. 5. 5. 6. 5. 5. 6. 5. 6. 6. 6. 6. 5. 6. 6. 5. 5. 5. 6. 6. 5. 5. 6. 5.
 6. 6. 5. 6. 5. 5. 5. 6. 6. 5. 5. 5. 6. 5. 6. 5. 6. 5. 6. 5. 5. 5. 6. 5.
 5. 6. 6. 5. 5. 6. 5. 5. 5. 5. 6. 5. 5. 6. 5. 6. 5. 6. 6. 6. 6. 6. 6. 6.
 6. 5. 5. 5. 6. 6. 6. 6. 6. 6. 5. 6. 5. 6. 6. 6. 5. 5. 6. 5. 6. 5. 6. 5.
 6. 5. 7. 5. 6. 5. 6. 6. 5. 6. 5. 6. 5. 5. 5. 6. 6. 6. 6. 5. 5. 6. 5. 6.
 5. 6. 5. 6. 5. 5. 6. 6. 6. 6. 5. 6. 5. 5. 6. 5. 6. 6. 5. 6. 6. 5. 6. 6.
 6. 6. 6. 6. 6. 6. 6. 5. 5. 5. 5. 6. 6. 5. 5. 6. 6. 5. 6. 6. 5. 6. 5. 6.
 5. 6. 6. 5. 5. 6. 6. 5. 5. 6. 5. 6. 6. 6. 5. 6. 6. 6. 5. 5. 5. 5. 5. 6.
 6. 5. 6. 6. 5. 5. 5. 6. 5. 6. 5. 6. 5. 6. 6. 5. 5. 5. 5. 6. 5. 6. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 6. 6. 6. 5. 5. 6. 6. 6. 5. 5. 5. 5. 5. 5. 5. 5. 6.
 5. 5. 6. 6. 6. 5. 5. 6. 5. 6. 5. 5. 6. 5. 5. 6. 6. 6. 5. 6. 6. 5. 6. 5.
 6. 6. 5. 5. 6. 6. 6. 6.]
[5. 5. 7. 8. 5. 4. 3. 5. 

In [11]:
acc_score = metrics.accuracy_score(y_pred,y_test)
print('acurracy:\n', acc_score)

acurracy:
 0.5625
