In [1]:
import numpy as np
#import matplotlib.pyplot as plt
# lacuong@it.tdt.edu.vn 

In [2]:
# Khởi tạo dữ liệu đầu vào X. Trong đó có X có 3 biến (x0, x1, x2) và 7 dòng dữ liệu
X = np.array([[1,2,3,4,5,6,7],
              [1.5,2.5,3.5,4.5,5.5,6.5,7.5]])
y = np.array([[2,4,6,8,10,12,14]])
print(X.shape)
one = np.ones((X.shape[1], 1))
print('one:\n',one)
X = np.array(X).T
print('X:\n',X)
X = np.concatenate((one,X),axis=1)
y = np.array(y).T
print('X new:\n',X)


(2, 7)
one:
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
X:
 [[1.  1.5]
 [2.  2.5]
 [3.  3.5]
 [4.  4.5]
 [5.  5.5]
 [6.  6.5]
 [7.  7.5]]
X new:
 [[1.  1.  1.5]
 [1.  2.  2.5]
 [1.  3.  3.5]
 [1.  4.  4.5]
 [1.  5.  5.5]
 [1.  6.  6.5]
 [1.  7.  7.5]]


In [3]:
# step 1: initialize and forward propagate  
# y = w0xi0 + w1xi1 + w2xi2
def f(X,W):
    # Tích của ma trận X và W
    return np.dot(X,W) 

In [4]:
# step 2: loss function 
def loss(X,Y):
    sum = 0
    for i in range(len(X)):
        sum += (f(X[i],W)-Y[i])**2
    return sum/len(X) 

In [5]:
#print(X.shape)
a = []
a.append(1)

In [6]:
# step 3: Differentiation
def derivate(X,Y,W):
    d=[]
    for k in range(X.shape[1]):
        sum = 0
        for i in range(X.shape[0]):
            sum += (f(X[i],W)-Y[i])*X[i][k]
        d.append(sum/X.shape[0])
    return np.array(d)

In [7]:
#test Thử nghiệm áp dụng gradient descent
W = np.array([[1,3.5,5]]).T
d = derivate(X,y,W)
print(d)
d = 0.1*d
print(d)
W=W-d
print(W)

[[ 29.5 ]
 [144.  ]
 [158.75]]
[[ 2.95 ]
 [14.4  ]
 [15.875]]
[[ -1.95 ]
 [-10.9  ]
 [-10.875]]


In [8]:
# step 4: update weight 
epoch = 50

# Độ bias
learning_rate = 0.01

# Mức xấp xỉ
epsilon = 0.01

# Khởi tạo Điểm đầu vào của w0 w1 w2 là 0
W = np.array([[0,0,0]]).T
for iter in range(epoch):
    before_loss = loss(X,y)
    print(iter,': ',before_loss) 
    
    #Gradient descent
    d = derivate(X,y,W)
    W = W-learning_rate*d
    
    # Nếu before_loss đạt cực tiểu thì thoát vòng lặp
    if before_loss-loss(X,y) < epsilon:
        break 
# print result 
print('W:')
print(W)
    

0 :  [80.]
1 :  [24.218]
2 :  [7.37449966]
3 :  [2.28839461]
4 :  [0.75241018]
5 :  [0.28837784]
6 :  [0.14802006]
7 :  [0.10539607]
8 :  [0.09228356]
W:
[[0.16838207]
 [0.88685178]
 [0.97104281]]
