In [1]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv("data/adult.data")
df=df.sample(n=200)

In [10]:
data = df.values
print(data.shape)
y = data[:, -1:]
y = y.ravel()
print(y[:3])

(200, 15)
[' <=50K' ' <=50K' ' <=50K']


In [12]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
y = LE.fit_transform(y)
print(y[:10])
y1 = y[y==1]
y0 = y[y==0]
print(y1)
print(y0)

[0 0 0 0 1 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]


In [17]:
dataX = df.select_dtypes(include=['float64', 'int64'])
print(dataX.shape)
print(dataX)
x = dataX.values
print(x)

(200, 6)
       39   77516   13   2174     0   40
19384  40  111971    9      0     0   30
27055  26  165235   13      0     0   40
19592  36  195516    9      0     0   40
15263  73   45784   10      0     0   11
27111  48   38240    9      0     0   40
...    ..     ...  ...    ...   ...  ...
27723  57   47857    9      0     0   40
16024  38   93206   13      0  1902   65
20489  52  194788   14   4787     0   60
10080  25  120238    9      0     0   40
10477  46  332355   10      0     0   40

[200 rows x 6 columns]
[[    40 111971      9      0      0     30]
 [    26 165235     13      0      0     40]
 [    36 195516      9      0      0     40]
 ...
 [    52 194788     14   4787      0     60]
 [    25 120238      9      0      0     40]
 [    46 332355     10      0      0     40]]


In [22]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(x)
X = scaler.transform(x)
print(X)

[[0.34848485 0.09853818 0.46153846 0.         0.         0.31506849]
 [0.13636364 0.16025519 0.76923077 0.         0.         0.45205479]
 [0.28787879 0.19534179 0.46153846 0.         0.         0.45205479]
 ...
 [0.53030303 0.19449826 0.84615385 0.04787048 0.         0.7260274 ]
 [0.12121212 0.10811716 0.46153846 0.         0.         0.45205479]
 [0.43939394 0.35389717 0.53846154 0.         0.         0.45205479]]


In [25]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=4)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(160, 6) (160,)
(40, 6) (40,)


In [26]:
from sklearn import svm

svm_classifier = svm.SVC(kernel='linear', gamma=0.01, C=100.)
svm_classifier.fit(X_train, y_train)

y_pred_svm = svm_classifier.predict(X_test)
print('predict:\n', y_pred_svm)
print('y_true:\n', y_test)

acc_score_svm = metrics.accuracy_score(y_pred_svm,y_test)
print('acurracy:\n', acc_score_svm)

predict:
 [0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1
 0 0 0]
y_true:
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0
 0 0 0]
acurracy:
 0.875
